ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls'),name='store'),
    path('store/',include('django.contrib.auth.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView


app_name = 'store'

urlpatterns = [

    path('favicon\.ico',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('',views.store,name='store'),
    path('cart/',views.cart,name='cart'),
    path('checkout/',views.checkout,name='checkout'),

    path('update_item/',views.updateUserOrder,name='update_item'),
    path('cart/update_item/',views.updateUserOrder,name='cart_update_item'),

    path('process_order/',views.processOrder,name='process_order'),

    path('signup/',views.SignUp.as_view(),name='signup'),
    path('store/login/',auth_views.LoginView.as_view(
    template_name = 'store/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),

    path('<int:pk>/',views.ProductDetailView.as_view(),name='product_detail'),
    path('my_orders/<int:pk>/',views.myOrder,name='myorders'),

    path('player/<str:name>',views.playerProduct,name='player'),
    path('player/update_item/',views.updateUserOrder,name='cart_update_item'),

]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import auth
from django.urls import reverse
# Create your models here.



class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=200,null=True)
    email = models.EmailField(max_length=100,null=True)

    def __str__(self):
        return self.name




class Product(models.Model):
    name = models.CharField(max_length=200,null=True)
    club = models.CharField(max_length=200,blank=True,null=True)
    year = models.CharField(max_length=200,blank=True,null=True)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    digital = models.BooleanField(default=False,null=True,blank=True)
    image = models.ImageField(null=True,blank=True)
    description = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = '/static'+self.image.url
        except:
            url = ''
        return url

    def get_absolute_url(self):
        return reverse("store:product_detail",kwargs = {'pk':self.pk})

class Order(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False,null=True,blank=True)
    transaction_id = models.CharField(max_length=200,null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitem = self.orderitem_set.all()
        for i in orderitem:
            if i.product.digital == False:
                shipping = True

        return shipping

    @property
    def get_cart_total(self):
        orderitem = self.orderitem_set.all()
        total = sum( item.get_total for item in orderitem)
        return total

    @property
    def get_cart_item(self):
        orderitem = self.orderitem_set.all()
        total = sum( item.quantity for item in orderitem)
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,blank=True,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    quantity = models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,null=True,blank=True)
    address = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200,null=True)
    state = models.CharField(max_length=200,null=True)
    pincode = models.CharField(max_length=200,null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.city)

store/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        help_texts = {
        'username' : None,
        'password1': None,
        'password2': None,
        }

    def __init__(self,*args,**kwargs):
        super(UserRegistrationForm,self).__init__(*args,**kwargs)
        self.fields['username'].label = 'UserName'
        self.fields['username'].widget.attrs['placeholder'] = 'Enter User Name'
        self.fields['email'].label = 'Email'
        self.fields['email'].widget.attrs['placeholder'] = "Enter Email Address"
        self.fields['password1'].label = 'Password'
        self.fields['password1'].widget.attrs['password1'] = 'Enter Password'
        self.fields['password2'].label = 'Confirm Password'
        self.fields['password2'].widget.attrs['password2'] = 'Re-Confirm Your Password'

store/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.models import AnonymousUser
from django.http import JsonResponse
import json
import datetime
from store.forms import UserRegistrationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView , DetailView
from store.utils import cookieCart , guestOrder
# Create your views here.


def store(request):
    print(request.user.username)
    if request.user.is_authenticated:
        customer , create = Customer.objects.get_or_create(user=request.user,name=request.user.username,email=request.user.email)
        customer = request.user.customer
        order , created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
        print('cartItems',cartItems)
    else:
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']


    products = Product.objects.all()[:8]
    context = {'products': products,'cartItems':cartItems , 'shipping':False}
    return render(request,'store/store.html',context)



def cart(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order , created = Order.objects.get_or_create(customer=customer , complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
        print(items)
    else:                                      #We are stroring values in cokies for AnonymousUser
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        order = cookieData['order']
        items = cookieData['items']

    context = {'items':items , 'order' : order,'cartItems':cartItems , 'shipping':False}
    return render(request,'store/cart.html',context)



def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order , created = Order.objects.get_or_create(customer=customer , complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
    else:
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']
        order = cookieData['order']
        items = cookieData['items']

    context = {'items':items , 'order' : order,'cartItems':cartItems , 'shipping':False}
    return render(request,'store/checkout.html',context)



def updateUserOrder(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('productId :', productId)
    print('action :', action)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order , created = Order.objects.get_or_create(customer=customer,complete=False)

    orderItem , created = OrderItem.objects.get_or_create(order=order,product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0 :
        orderItem.delete()


    return JsonResponse("Sending Json data",safe=False)




def processOrder(request):
    print('Data :',request.body)
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order , created = Order.objects.get_or_create(customer=customer,complete=False)

    else:
        customer , order = guestOrder(request,data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            pincode = data['shipping']['pincode']
        )

    return JsonResponse("Payment Completed",safe=False)


class SignUp(CreateView):
    form_class = UserRegistrationForm
    template_name = 'store/signup.html'
    success_url = reverse_lazy('login')


class ProductDetailView(DetailView):
    context_object_name = 'product_detail'
    model = Product
    template_name = 'store/product_detail.html'


def myOrder(request,pk):
    try:
        if request.user.is_authenticated:
            customer = request.user.customer
            cur_order = Order.objects.get(customer=customer,complete=False)  #for current order , getting order id
            cur_items = cur_order.orderitem_set.all()                        #for current order id , getting all items of the order id
            cartItems = cur_order.get_cart_item                              # getting cart item count for current order
            print(cartItems)
            '''
            orderItem = []
            order = Order.objects.filter(customer=customer,complete=True)   #getting all order of loginin customer
            for myorder in order:
                item = myorder.orderitem_set.all()                          #getting items for each order
                orderItem.append(item)
            '''
            order = Order.objects.filter(customer=customer,complete=True)
            orderItem = OrderItem.objects.filter(order__in=order)
            print("OrderItem",orderItem[0].product.price)
    except:
        order = 0
        orderItem = 0
        cartItems = cur_order.get_cart_item
    context = {'order':order,'orderItem':orderItem,'cartItems':cartItems}
    return render(request,'store/myOrder.html',context)



def playerProduct(request,name):
    if request.user.is_authenticated:
        customer = request.user.customer
        order , created = Order.objects.get_or_create(customer=customer,complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_item
        mes = 0
        cris = 0

        if name == 'cristiano':
            cris = Product.objects.filter(name='Cristiano Ronaldo')

        if name == 'messi':
            mes = Product.objects.filter(name='Lionel Messi')


        print('player',cris)
        print('messi',mes)
    else:
        mes = 0
        cris = 0
        if name == 'cristiano':
            cris = Product.objects.filter(name='Cristiano Ronaldo')

        if name == 'messi':
            mes = Product.objects.filter(name='Lionel Messi')


        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']

    context = {'cris':cris,'cartItems':cartItems , 'shipping':False,'mes':mes}
    return render(request,'store/player.html',context)

store/templates/store/cart.html
{% extends "store/main.html" %}
{% load static %}

{% block content %}

  <div class="w3-row w3-content w3-large w3-card-4 w3-mobile" style="margin-top:50px;margin-bottom:50px;font-family:Arial, Helvetica, sans-serif;font-size:19px">
    <div class="w3-container w3-mobile w3-margin-top w3-margin-bottom">
      <a href="{% url 'store:store' %}" class="w3-mobile w3-btn w3-round-large w3-text-white w3-margin-top w3-hover w3-hover-text-cyan"
        style="background-color:#1877f2">&#x2190; Continue Shopping</a>
    </div>
    <table class="w3-table w3-mobile w3-margin-top w3-margin-bottom">
      <tr>
        <th><h5 class="w3-text-black">Items : <strong>{{order.get_cart_item}}</strong> </h5></th>
        <th><h5 class="w3-text-black">Total : <strong>{{order.get_cart_total}}</strong> </h5></th>
        <th>
          <a href="{% url 'store:checkout' %}" class="w3-right w3-btn w3-round-large w3-text-white w3-hover w3-hover-text-cyan"
            style="background-color:#1877f2">Checkout</a>
        </th>
      </tr>
    </table>
  </div>


  <!--<div class="w3-row w3-container w3-card-4 w3-margin w3-mobile">
      <div class="cart-row w3-padding w3-mobile">
        <div class="w3-content w3-mobile" style="flex:1"></div>
        <div class="w3-content w3-mobile" style="flex:1"><strong>Item</strong></div>
        <div class="w3-content w3-mobile" style="flex:1"><strong>Price</strong></div>
        <div class="w3-content w3-mobile" style="flex:1"><strong>Quantity</strong></div>
        <div class="w3-content w3-mobile" style="flex:1"><strong>Total</strong></div>
      </div>
      {% for item in items %}
      <div class="cart-row w3-padding w3-display-container w3-mobile">
        <div class="w3-content w3-mobile" style="flex:1"><img src="{{item.product.imageURL}}" class="thumbnail-row" alt="placeholder"> </div>
        <div class="content" style="flex:1"><strong>{{item.product.name}}</strong></div>
        <div class="content" style="flex:1"><strong>$ {{item.product.price|floatformat:2}}</strong></div>
        <div class="quan" style="flex:1">
          <p class="quantity">{{item.quantity}}</p>
          <div class="quantity">
            <img data-product = {{item.product.id}} data-action = "add" src="{% static 'images/arrow-up.png' %}" alt="arrow-up" class="chg-quantity update-cart">
            <img data-product = {{item.product.id}} data-action = "remove" src="{% static 'images/arrow-down.png' %}" alt="arrow-down" class="chg-quantity update-cart">
          </div>
        </div>
        <div class="content" style="flex:1"><strong>$ {{item.get_total}}</strong></div>
      </div>
      {% endfor %}
  </div>-->
  <div class="w3-card-4 w3-mobile w3-content" style="margin-bottom:500px;font-family:Arial, Helvetica, sans-serif;font-size:19px">
  {% for item in items %}
  <div class="w3-row w3-display-container w3-mobile w3-padding ">
    <div class="w3-col l3 s3 m3 w3-center"><strong>Display</strong></div>
    <div class="w3-col l3 s3 m3 w3-center"><strong>Item</strong></div>
    <div class="w3-col l2 s2 m2 w3-center"><strong>Price</strong></div>
    <div class="w3-col l2 s2 m2 w3-center"><strong>Quantity</strong></div>
    <div class="w3-col l2 s2 m2 w3-center"><strong>Total</strong></div>
  </div>
  <div class="w3-row-padding w3-display-container w3-mobile w3-padding">
    <div class="w3-col l3 s3 m3"><img src="{{item.product.imageURL}}" class="thumbnail-row" alt="placeholder"></div>
    <div class="w3-col l3 s3 m3 w3-center content"><strong>{{item.product.name}}</strong></div>
    <div class="w3-col l2 s2 m2 w3-center content"><strong>&#8377;{{item.product.price|floatformat:2}}</strong></div>
    <div class="w3-col l2 s2 m2 w3-center content">
      <span class="quantity">{{item.quantity}}</span>
      <div class="quantity">
        <img data-product = {{item.product.id}} data-action = "add" src="{% static 'images/arrow-up.png' %}" alt="arrow-up" class="chg-quantity update-cart">
        <img data-product = {{item.product.id}} data-action = "remove" src="{% static 'images/arrow-down.png' %}" alt="arrow-down" class="chg-quantity update-cart">
      </div>
    </div>
    <div class="w3-col l2 s2 m2 w3-center content"><strong>&#8377;{{item.get_total}}</strong></div>
  </div><br><hr>
  {% endfor %}
</div>
<div class="w3-container w3-hide-large">
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <br><br>
</div>
{% include 'store/footer.html' %}
{% endblock content %}

store/templates/store/login.html
{% extends 'store/main.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="w3-content w3-mobile w3-hide-medium w3-hide-small w3-large w3-round"
style="width:500px;height:500px;max-width:1500px;margin-top:120px;margin-bottom:100px">

  <form class=" w3-card-4 w3-padding w3-mobile w3-round-large w3-animate-top" method="POST"
  style="margin-top : 25px;font-family:Arial, Helvetica, sans-serif;font-size:19px">
    <div class="w3-container w3-margin-bottom w3-margin-top w3-center w3-mobile" style="background-color:#1877f2">
      <h1 class="w3-text-white w3-mobile">SIGN IN</h1>
    </div>
    {% csrf_token %}
    {{form|crispy}}<br>
    <div class="w3-center w3-margin">
      <input type="submit" name="" value="Sign In" class="w3-btn w3-block w3-round-xlarge w3-text-white w3-hover w3-hover-text-cyan"
      style="background-color:#1877f2">
    </div>
    <div class="w3-center">
      <label for="">Don't have Account ? Register Here</label>
      <a href="{% url 'store:signup' %}" class="w3-btn w3-round-xlarge w3-text-white w3-hover w3-hover-text-cyan w3-margin-bottom"
      style="background-color:#1877f2"">Register</a>
    </div>
  </form>
</div>

<div class="w3-content w3-mobile w3-hide-large w3-xlarge w3-round"
style="width:700px;height:700px;max-width:1500px;margin-top:450px;margin-bottom:430px">

  <form class=" w3-card-4 w3-padding w3-mobile w3-round-xlarge w3-animate-top" method="POST"
  style="margin-top : 25px;font-family:Arial, Helvetica, sans-serif;font-size:19px">
    <div class="w3-container w3-margin-bottom w3-margin-top w3-center w3-mobile" style="background-color:#1877f2">
      <h2 class="w3-text-white w3-mobile">SIGN IN</h2>
    </div>
    {% csrf_token %}
    {{form|crispy}}<br>
    <div class="w3-center w3-margin">
      <input type="submit" name="" value="Sign In" class="w3-btn w3-block w3-round-xlarge w3-text-white w3-hover w3-hover-text-cyan"
      style="background-color:#1877f2">
    </div>
    <div class="w3-center">
      <label for="">Don't have Account ? Register Here</label>
      <a href="{% url 'store:signup' %}" class="w3-btn w3-round-xlarge w3-text-white w3-hover w3-hover-text-cyan w3-margin-bottom"
      style="background-color:#1877f2"">Register</a>
    </div>
  </form>
</div>
{% include 'store/footer.html' %}
{% endblock %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Shopify</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
                                        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Archivo Black' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script type="text/javascript">
      var user = '{{request.user}}'
      function getCookie(name) {
          var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
          }
      var csrftoken = getCookie('csrftoken');

      function getCookie(name){
        //Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");

        //Loop through the array elements
        for(var i = 0; i < cookieArr.length; i++){
          var cookiePair = cookieArr[i].split("=");

          /* Removing whitespaces at the beginning of the cokie name
          and compare it with the given string */
          if (name == cookiePair[0].trim()){
            //Decode the cokie value and return
            return decodeURIComponent(cookiePair[1]);
          }
        }
        //return null if not found
        return null;
      }

      var cart = JSON.parse(getCookie('cart'))
      if(cart == undefined){
          cart = {}
          console.log('Cart was created!')
          document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
      }
      console.log('Cart:',cart);
    </script>

  </head>
  <body>
  <div class="w3-content" style="max-width:2000px">
    <div class="w3-bar w3-mobile w3-padding " style="background-color:#1877f2;font-family:Arial, Helvetica, sans-serif;font-size:22px">
      <a href="{% url 'store:store' %}" class="w3-bar-item w3-btn w3-round w3-ripple w3-hover w3-text-white w3-hover-text-cyan">Shopify</a>
      <!--<a href="{% url 'store:store' %}" class="w3-bar-item w3-btn w3-round w3-ripple w3-hover w3-text-white w3-hover-text-cyan w3-hide-small">Store</a>-->
      <div class="w3-dropdown-hover">
        <button class="w3-btn w3-round w3-ripple w3-hover w3-text-white w3-hover-text-cyan">Players <i class="fa fa-caret-down"></i> </button>
        <div class="w3-dropdown-content w3-bar-block" style="background-color:#1877f2">
          <a href="{% url 'store:player' 'cristiano' %}" class="w3-bar-item w3-btn w3-round w3-ripple w3-hover w3-hover-cyan w3-text-white w3-hover-text-white">Cristiano</a>
          <a href="{% url 'store:player' 'messi' %}" class="w3-bar-item w3-btn w3-round w3-ripple w3-hover w3-hover-cyan w3-text-white w3-hover-text-white">Messi</a>
        </div>
      </div>
      <a href="javascript:void(0)" class="w3-bar-item w3-btn w3-round-xlarge w3-xlagre w3-ripple w3-right w3-text-white w3-cyan w3-hide-large" onclick="myFunction()">&#9776;</a>
      <div class="w3-margin-right w3-hide-medium">
        <span id="cart-total" class="w3-right w3-hide-small w3-cyan w3-text-white">{{cartItems}}</span>
        <a href="{% url 'store:cart' %}" class="w3-mobile w3-hide-small w3-right w3-ripple">
          <img src="{% static 'images/cart1.png' %}" alt="CART" id="cart-icon" class="w3-hover">
        </a>
      </div>
      {% if user.is_authenticated %}
      <a href="{% url 'store:logout' %}" class="w3-btn w3-round-large w3-right w3-mobile w3-hide-small w3-hide-medium w3-hover w3-text-white w3-hover-text-cyan w3-ripple ">LOGOUT</a>
      <!--<a href="#" class="w3-btn w3-right w3-mobile w3-round-large w3-hide-small
      w3-hover w3-text-white w3-hover-text-cyan w3-ripple">{{user.username}}</a>-->
      <a href="{% url 'store:myorders' user.customer.id %}" class="w3-btn w3-right w3-mobile w3-round-large w3-hide-small w3-hide-medium w3-hover w3-text-white w3-hover-text-cyan w3-ripple">My Orders</a>
      {% else %}
      <a href="{% url 'store:login' %}" class="w3-btn w3-round-large w3-right w3-mobile w3-hide-small w3-hide-medium w3-ripple w3-text-white w3-hover-text-cyan">Login</a>
      {% endif %}
      </div>
    </div>
    <div class="w3-side-bar w3-bar-block w3-hide  w3-hide-large" id="demo" style="background-color:#1877f2;font-family:Arial, Helvetica, sans-serif;font-size:22px;">
      <a href="{% url 'store:store' %}" class="w3-bar-item w3-btn w3-text-cyan w3-hide-small w3-hide-medium w3-hover-text-white w3-ripple">Shopify</a>
      <a href="{% url 'store:cart' %}" class="w3-bar-item w3-btn w3-text-cyan w3-round-large w3-hover-cyan w3-ripple w3-hover-text-white">
        <span id="cart-small" class="w3-text-white w3-hover-text-black w3-hover-red">{{cartItems}}</span>
        <img src="{% static 'images/cart1.png' %}" alt="CART" id="cart-small-icon" class="w3-xxlarge">
      </a>
      {% if user.is_authenticated %}
      <a href="{% url 'store:myorders' user.customer.id %}" class="w3-bar-item w3-btn w3-text-cyan w3-round-large w3-hover-text-white w3-hover-cyan w3-ripple">My Orders</a>
      <a href="{% url 'store:logout' %}" class="w3-bar-item w3-btn w3-text-cyan w3-round-large w3-hover-text-white w3-hover-cyan w3-ripple ">Logout</a>
      {% else %}
      <a href="{% url 'store:login' %}" class="w3-bar-item w3-btn w3-text-cyan w3-round-large w3-hover-cyan w3-ripple w3-hover-text-white">Login</a>
      {% endif %}
    </div>



  <div class="w3-container">
    {% block content %}


    {% endblock content %}
  </div>
</div>



  <script>
    function myFunction() {
      var x = document.getElementById("demo");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace(" w3-show", "");
      }
    }
  </script>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>

  <script type="text/javascript" src="{% static 'js/cart.js'  %}"></script>


  </body>
</html>

store/templates/store/thanks.html
THANKS